enum ScheduleActionTypes {
  FETCH_SCHEDULE_START = 'FETCH_SCHEDULE_START',
  FETCH_SCHEDULE_SUCCESS = 'FETCH_SCHEDULE_SUCCESS',
  FETCH_SCHEDULE_FAILURE = 'FETCH_SCHEDULE_FAILURE',
};

export default ScheduleActionTypes;