enum LoginActionTypes {
  FETCH_LOGIN_START = 'FETCH_LOGIN_START',
  FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS',
  FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE',
  FETCH_YOUTUBE_CHECK_START = 'FETCH_YOUTUBE_CHECK_START',
  FETCH_YOUTUBE_CHECK_SUCCESS = 'FETCH_YOUTUBE_CHECK_SUCCESS',
  FETCH_YOUTUBE_CHECK_FAILURE = 'FETCH_YOUTUBE_CHECK_FAILURE',
}

export default LoginActionTypes;