enum MemberActionTypes {
  FETCH_MEMBER_START = 'FETCH_MEMBER_START',
  FETCH_MEMBER_SUCCESS = 'FETCH_MEMBER_SUCCESS',
  FETCH_MEMBER_FAILURE = 'FETCH_MEMBER_FAILURE',
}

export default MemberActionTypes;